server:
  port: 80


#从applicaion.yml文件中拷贝过来，不需要修改的就在这里把它们删除掉，然后在原文件中将相同的注释掉

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: 123456